name: Notification on push

on:
  push:
    branches:
      - master
      - main # ✊🏿

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Slack notification SUCCESS
        uses: kisaan-pk/custom_google_chat_v2@v4
        env:
          SERVICE_NAME: User
          SOURCE: Github Action
          ENVIRONMENT: Production
          PULL_REQUEST: ${{ github.event.pull_request.title }}
        with:
          args: "Lint checks *SUCCESSFUL!*\nfrom {{ GITHUB_ACTOR }} at {{ GITHUB_REPOSITORY }}"
