name: Notification on push

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  CI: true

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: kceb/pull-request-url-action@v1
        id: pr-url
      - uses: actions/checkout@v4
      - name: Slack notification SUCCESS
        uses: kisaan-pk/custom_google_chat_v2@v1
        env:
          SERVICE_NAME: User
          SOURCE: Github Action
          ENVIRONMENT: Production
          PULL_REQUEST: ${{ github.event.pull_request.title }}
          PR_URL: ${{ steps.pr-url.outputs.url }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        with:
          args: "Lint checks *SUCCESSFUL!*\nfrom {{ GITHUB_ACTOR }} at {{ GITHUB_REPOSITORY }}"
